### ISSUE TITLE
Unordered expectations

### ISSUE THREAD

**Issue by felixvisee** [rheinfabrik/Dobby#19]
Allowing expectations to be fulfilled out of order might be useful.

**Comment by tibr** [comment]
There are two solutions I can think of:

a) We change `expectations` to be a `Set` instead of an `Array`. This would mean that no interaction can be expected multiple times.
b) We leave `expectations` as `Array`. The trivial solution for this would be to create a copy of `expectations` in `verify()` and remove individual expectations from it when verifying. This would have the added benefit of allowing the check of multiple invocations of the same interaction.

What do you think @felixjendrusch ?
